# Generated by Django 4.1.2 on 2022-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpeningTitle', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('Pipelined', models.IntegerField(default=0)),
                ('PublishedSites', models.CharField(max_length=50)),
                ('PrimaryRecruiter', models.CharField(max_length=50)),
                ('Priority', models.IntegerField(default=0)),
                ('TotalOpening', models.IntegerField(default=0)),
                ('PostDate', models.DateField()),
            ],
        ),
    ]
