# Generated by Django 4.1.2 on 2022-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantTracking', '0002_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateName', models.CharField(max_length=100)),
                ('SubmittedDate', models.DateField()),
                ('Status', models.CharField(max_length=50)),
                ('OpeningTitle', models.CharField(max_length=50)),
                ('OpeningID', models.CharField(max_length=10)),
                ('AccountName', models.CharField(max_length=50)),
                ('OpeningPostDate', models.DateField()),
                ('OpeningStatus', models.CharField(max_length=50)),
                ('SourcedFrom', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField(max_length=15)),
                ('Qualification', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
