# Generated by Django 4.1.2 on 2022-10-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantTracking', '0003_pipeline_alter_candidates_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlacementName', models.CharField(max_length=100)),
                ('BillRate', models.CharField(max_length=25)),
                ('CandidateName', models.CharField(max_length=100)),
                ('OpeningTitle', models.CharField(max_length=100)),
                ('EndClient', models.CharField(max_length=100)),
                ('ProjectEndDate', models.DateField()),
                ('ProjectStartDate', models.DateField()),
                ('SourcedFrom', models.CharField(max_length=50)),
                ('NetMargin', models.CharField(max_length=50)),
                ('SalesMargin', models.CharField(max_length=50)),
                ('OpeningID', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=50)),
                ('PlacedBy', models.CharField(max_length=50)),
                ('PlacedOn', models.CharField(max_length=50)),
            ],
        ),
    ]
