# Generated by Django 4.1.2 on 2022-10-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantTracking', '0004_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('AccountOwner', models.CharField(max_length=100)),
                ('AccountCode', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Access', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
        ),
    ]
