# Generated by Django 4.1.2 on 2022-10-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicantTracking', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
